config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resource :account do
    resource :email do
      get :confirmation, on: :member
    end
    resources :confirmations
  end

  resources :points do
    collection do
      get "bonus", action: :bonuses, as: "bonuses"
      get "bonus/:key", :action => :bonus, :key => /[a-z0-9]+/, :as => "bonus"
      put "bonus/:key", :action => :update_bonuses, :key => /[a-z0-9]+/, :as => "update_bonuses"
      post "bonus/:key", :action => :award_bonus_to_all, :key => /[a-z0-9]+/, :as => "award_bonus_to_all"
      post "assign_all_bonuses_bonuses"
    end
    post :split, on: :member
  end

  get "leader-board/:year" => "teams#index", :year => nil, :as => "leader_board"
  get "leader-board/:year/:position" => "teams#show", :as => "leader_board_laps"

  match "/admin/jobs" => DelayedJobWeb, anchor: false, via: [:get, :post]

  get "admin" => redirect("/admin/site")

  namespace :admin do
    resource :confirmation_email
    resources :races do
      resources :bonuses do
        put "", action: :sortable, on: :collection
        post :delete_all, on: :collection
      end
      resources :teams, except: :show do
        post :send_confirmation_emails, :on => :collection
      end
    end
    resources :users do
      post :resend_confirmation
    end
    resource :database
  end
end

app/controllers/admin/bonuses_controller.rb
class Admin::BonusesController < Admin::BaseController
  before_action :set_race

  def sortable
    new_bonuses = params[:bonuses].map do |json|
      bonus = JSON.parse(json).to_hash
      bonus.delete("id")
      bonus
    end
    @race.update! bonuses: new_bonuses
    render json: true
  end

  def show
    @bonus = Bonus.find_by_race_and_id(@race, params[:id])
    @bonuses = Point.bonuses.where(bonus_id: params[:id], race_id: @race.id).includes(:team).reorder("teams.position")
  end

  def new
    @bonus = Bonus.new(points: 2)
    render :form
  end

  def edit
    @bonus = Bonus.find_by_race_and_id(@race, params[:id])
    render :form
  end

  def create
    if params[:id].present?
      update
    else
      params[:bonus][:key] = SecureRandom.hex(8)
      @race.bonuses << params[:bonus]
      @race.save
      redirect_to [:new, :admin, @race, :bonus], notice: "Bonus added! Add another?"
    end
  end

  def update
    @race.bonuses[params[:id].to_i][:name] = params[:bonus][:name]
    @race.bonuses[params[:id].to_i][:points] = params[:bonus][:points]
    @race.save
    redirect_to [:edit, :admin, @race], notice: "Bonus updated!"
  end

  def delete_all
    @race.bonuses = []
    @race.save
    redirect_to [:edit, :admin, @race], notice: "All Bonuses deleted!"
  end

  private

  def set_menu
    @menu = Menus::Admin::Teams.new
  end

  def set_race
    @race = Race.find(params[:race_id])
  end
end

app/views/admin/bonuses/form.html.haml
%h2
  = params[:action].titleize
  Bonus
  = @bonus.id

= form_for [:admin, @site, @race, @bonus] do |form|
  %p
    = form.label :name
    = form.text_field :name

  %p
    = form.label :points
    = form.text_field :points

  %br

  %p
    %input(type="submit" value="#{@bonus.new_record? ? "Create Bonus" : "Update Bonus"}")
    = link_to "cancel", [:edit, :admin, @site, @race]

:coffeescript
  $ ->
    $("#bonus_name").focus()

app/views/admin/bonuses/form.html.slim
h2
  = params[:action].titleize
  | Bonus
  = @bonus.id

= form_for [:admin, @race, @bonus] do |form|
  p
    = form.label :name
    = form.text_field :name, autofocus: true

  p
    = form.label :points
    = form.text_field :points

  br

  p
    input type="submit" value=(@bonus.new_record? ? "Create Bonus" : "Update Bonus")
    = link_to "cancel", [:edit, :admin, @race]

app/views/admin/bonuses/new.html.haml
= form_for [:admin, @site, @race, @bonus] do |form|
  %p
    = form.label :name
    = form.text_field :name

  %p
    = form.label :points
    = form.text_field :points

  %p
    = form.submit
    = link_to "cancel", [:edit, :admin, @site, @race]

:coffeescript
  $ ->
    $("#bonus_name").focus()

app/views/admin/bonuses/show.html.slim
h2 Bonus ##{@bonus.id} - #{@bonus.name}

table#bonus-view
  - @bonuses.each do |bonus|
    tr id=dom_id(bonus)
      th = bonus.team_position
      td = bonus.team_name
      td = bonus.qty
      td = link_to "Delete", point_path(bonus), class: "delete-icon", remote: true, method: :delete, data: { type: "text", confirm: "Are you sure?", controller: "delete-bonus" }