config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resource :account do
    resource :email do
      get :confirmation, on: :member
    end
    resources :confirmations
  end

  resources :points do
    collection do
      get "bonus", action: :bonuses, as: "bonuses"
      get "bonus/:key", :action => :bonus, :key => /[a-z0-9]+/, :as => "bonus"
      put "bonus/:key", :action => :update_bonuses, :key => /[a-z0-9]+/, :as => "update_bonuses"
      post "bonus/:key", :action => :award_bonus_to_all, :key => /[a-z0-9]+/, :as => "award_bonus_to_all"
      post "assign_all_bonuses_bonuses"
    end
    post :split, on: :member
  end

  get "leader-board/:year" => "teams#index", :year => nil, :as => "leader_board"
  get "leader-board/:year/:position" => "teams#show", :as => "leader_board_laps"

  match "/admin/jobs" => DelayedJobWeb, anchor: false, via: [:get, :post]

  get "admin" => redirect("/admin/site")

  namespace :admin do
    resource :confirmation_email
    resources :races do
      resources :bonuses do
        put "", action: :sortable, on: :collection
        post :delete_all, on: :collection
      end
      resources :teams, except: :show do
        post :send_confirmation_emails, :on => :collection
      end
    end
    resources :users do
      post :resend_confirmation
    end
    resource :database
  end
end

app/models/race.rb
require "active_record/json_associations"

class Race < ActiveRecord::Base
  belongs_to_many :categories, class_name: "TeamCategory"
  has_many :teams
  has_many :riders, :through => :teams
  has_many :points

  store :settings

  serialize :shirt_sizes, coder: JSON, type: Array, default: %w[XS S M L XL XXL XXXL]

  def self.published
    where(published: true).order(year: :desc)
  end

  def self.current
    last
  end

  def running?
    started? and not finished?
  end

  def started?
    DateTime.now > start_time
  end

  def finished?
    DateTime.now > end_time
  end

  def end_time
    start_time + 24.hours
  end

  def bonuses
    settings[:bonuses] ||= []
  end

  def bonuses= value
    settings[:bonuses] = value
  end

  def bonus_checkpoints
    bonuses.map.with_index do |attributes, index|
      Bonus.new(attributes.merge(id: index))
    end
  end

  def assign_all_bonuses_bonuses
    tattoo_points = bonus_checkpoints.first.points.to_i
    raise AllBonusesException, "The first bonus needs to be a five point tattoo bonus" unless tattoo_points == 5
    all_bonuses_points = bonus_checkpoints.last.points.to_i
    raise AllBonusesException, "The last bonus needs to be a five point all bonuses bonus" unless all_bonuses_points == 5

    teams.find_each do |team|
      assigned_bonuses = team.points.bonuses.map(&:bonus_id).sort
      before = (1..bonus_checkpoints.count-2).to_a
      after = (1..bonus_checkpoints.count-1).to_a
      all_bonuses_bonus = team.points.where(qty: 5, category: "Bonus", race: self, bonus_id: bonus_checkpoints.last.id)

      if [before, after].include?(assigned_bonuses)
        all_bonuses_bonus.first_or_create!
      else
        all_bonuses_bonus.destroy_all
      end
    end
  end

  def total_laps
    points.laps.sum(:qty)
  end

  def total_miles
    total_laps * BigDecimal("4.6")
  end

  def shirt_size_counts
    teams.inject({}) do |counts, team|
      team.shirt_sizes.attributes.each do |size, count|
        counts[size.to_s] ||= 0
        counts[size.to_s] += count.to_i
      end
      counts
    end
  end

  def rider_autocomplete_options
    user_team_map = riders.includes(:team).inject({}) do |map, rider|
      if rider.user_id
        map.merge rider.user_id => rider.team.position
      else
        map
      end
    end

    User.all.map do |user|
      {
        verified: user.verified?,
        label: "#{user.name} ‹#{user.email}›",
        value: user.id,
        user_id: user.id,
        name: user.name,
        email: user.email,
        phone: user.phone,
        shirt_size: user.shirt_size,
        team_pos: user_team_map[user.id],
      }
    end
  end
end

class AllBonusesException < StandardError; end

app/controllers/admin/races_controller.rb
class Admin::RacesController < Admin::BaseController
  def index
    @races = Race.order(year: :desc)
    if @races.none?
      redirect_to action: :new
    end
  end

  def new
    @race = Race.new
    render :form
  end

  def edit
    race
    render :form
  end

  def create
    @race = Race.new(params[:race].merge(category_ids: Race.last&.category_ids))
    if @race.save
      @site.touch # expire all cached pages
      redirect_to [:admin, @race, :teams], notice: "Race created!"
    else
      render :form
    end
  end

  def update
    if race.update(params[:race])
      @site.touch # expire all cached pages
      redirect_to [:admin, @race, :teams], notice: "Race updated!"
    else
      render :form
    end
  end

  private

  def race
    @race ||= Race.find_by_id(params[:id])
  end

  def set_menu
    @menu = Menus::Admin::Races.new
  end
end

app/views/admin/races/_bonuses.html.slim
h3 Bonus Checkpoints

table#bonuses.list
  thead
    tr
      th #
      th Name
      th Points
      th
      th
  tbody data-controller="sortable"
    - @race.bonus_checkpoints.each do |bonus|
      tr data-attributes=bonus.to_json
        td
          span
        td = link_to bonus.name, admin_race_bonus_path(@race, bonus.id)
        td = bonus.points
        td = link_to "Bonus Form", bonus_points_path(key: bonus.key)
        td
          = link_to "Edit", edit_admin_race_bonus_path(@race, bonus.id), class: "edit"
          / input.delete type="submit" value="Delete"

app/views/admin/races/form.html.haml
.col.half
  %h3 Basic Information

  %hr

  = form_for [:admin, @race] do |form|

    .field#race-title
      = form.label :year
      = form.text_field :year

    .field#starts
      = form.label :start_time
      = form.datetime_field :start_time, ampm: true

    .field
      = form.check_box :published, label: "Show race in leaderboards dropdown menu?"

    %hr


    .field#description
      = form.label :description
      %p This will be shown at the top of the leaderboard.
      .clear
      = form.text_area :description, class: "wysiwyg"

    .field
      %input.save(type="submit" value="Save")
      = link_to "cancel", :back, class: "cancel"

- if @race.persisted?
  = content_for :sidebar do
    .tabs
      .tab.active
        = render "bonuses"
        %p.right_align.clear= link_to "+ Add a Checkpoint", [:new, :admin, @race, :bonus]
        %p= button_to "Delete All Bonuses", [:delete_all, :admin, @race, :bonuses], data: { confirm: "Are you sure you want to remove all the bonuses?" }

app/views/admin/races/index.html.slim
h2 Races

table.race-list
  thead
    tr
      th Year
      th
  tbody
    - @races.each do |race|
      tr
        td = link_to race.year, [:admin, race, :teams]
        td.actions
          = link_to "Edit Race", [:edit, :admin, race], class: "edit"
          / = link_to "Delete Race", [:admin, race], method: :delete, class: "delete", data: { confirm: "Are you sure you want to delete this race and all its teams and riders?" }