config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resource :account do
    resource :email do
      get :confirmation, on: :member
    end
    resources :confirmations
  end

  resources :points do
    collection do
      get "bonus", action: :bonuses, as: "bonuses"
      get "bonus/:key", :action => :bonus, :key => /[a-z0-9]+/, :as => "bonus"
      put "bonus/:key", :action => :update_bonuses, :key => /[a-z0-9]+/, :as => "update_bonuses"
      post "bonus/:key", :action => :award_bonus_to_all, :key => /[a-z0-9]+/, :as => "award_bonus_to_all"
      post "assign_all_bonuses_bonuses"
    end
    post :split, on: :member
  end

  get "leader-board/:year" => "teams#index", :year => nil, :as => "leader_board"
  get "leader-board/:year/:position" => "teams#show", :as => "leader_board_laps"

  match "/admin/jobs" => DelayedJobWeb, anchor: false, via: [:get, :post]

  get "admin" => redirect("/admin/site")

  namespace :admin do
    resource :confirmation_email
    resources :races do
      resources :bonuses do
        put "", action: :sortable, on: :collection
        post :delete_all, on: :collection
      end
      resources :teams, except: :show do
        post :send_confirmation_emails, :on => :collection
      end
    end
    resources :users do
      post :resend_confirmation
    end
    resource :database
  end
end

app/views/admin/users/_form.html.slim
fieldset.-padded
  .flex
    .field
      = f.label :email
      p
        b = f.object.email
    .field
      = f.check_box :admin, label: " Admin?"

  .flex
    .field = f.text_field :first_name, label: "First name"
    .field = f.text_field :last_name, label: "Last name"
  .flex
    .field = f.email_field :email, label: "Email"
    .field = f.text_field :phone, label: "Phone"

  .flex
    - if current_race
      .field
        /= form.label :shirt_size
        = f.select :shirt_size, current_race.shirt_sizes, include_blank: true, label: "Shirt size"
    .field
      / = f.text_field :homepage, label: "Homepage"
  .help-text Leave Password blank to keep existing
  .field
    = f.password_field :password, label: "Password"

- save_or_cancel_links f, cancel_url: admin_users_path

app/views/admin/users/index.html.slim
.table-buttons
  = link_to "Download users", [:admin, :users, format: :csv], class: "download-button"

table.users-table
  thead
    tr
      th Name
      th Email
      th Confirmed?
      th Role
      th Shirt
      th Races
      th
  tbody
    - @users.each do |user|
      tr
        td = link_to user.name, [:admin, user]
        td = user.email
        td = user.verified? ? "Yes" : link_to("Resend", [:admin, user, :resend_confirmation], method: :post)
        td = "Admin" if user.admin?
        td = user.shirt_size
        td
          - @user_teams[user.id].each do |race_id, team_id|
            - year = @user_teams.race_year_map[race_id]
            = link_to year, edit_admin_race_team_path(race_id, team_id), class: "user-race"
        td
          = link_to "Edit user", [:edit, :admin, user], class: "edit-icon", title: "Edit user"
          = link_to "Delete user", [:admin, user], method: "delete", class: "delete-icon", title: "Delete user",
            data: { confirm: "Are you sure you want to delete this user?" }

app/views/admin/users/show.html.slim
h3 Details
h2 = @user.name

p
  | Email:&nbsp;
  = @user.email

p
  | Phone:&nbsp;
  = @user.phone

p
  | Shirt size:&nbsp;
  = @user.shirt_size

- if @user.homepage
  p
    | Homepage:&nbsp;
    = link_to @user.homepage, @user.homepage, target: "_blank"

hr
h3 Events
p
  | Created at:&nbsp;
  = @user.created_at

p
  | Updated at:&nbsp;
  = @user.updated_at


= render :partial => 'sidebar'