config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resource :account do
    resource :email do
      get :confirmation, on: :member
    end
    resources :confirmations
  end

  resources :points do
    collection do
      get "bonus", action: :bonuses, as: "bonuses"
      get "bonus/:key", :action => :bonus, :key => /[a-z0-9]+/, :as => "bonus"
      put "bonus/:key", :action => :update_bonuses, :key => /[a-z0-9]+/, :as => "update_bonuses"
      post "bonus/:key", :action => :award_bonus_to_all, :key => /[a-z0-9]+/, :as => "award_bonus_to_all"
      post "assign_all_bonuses_bonuses"
    end
    post :split, on: :member
  end

  get "leader-board/:year" => "teams#index", :year => nil, :as => "leader_board"
  get "leader-board/:year/:position" => "teams#show", :as => "leader_board_laps"

  match "/admin/jobs" => DelayedJobWeb, anchor: false, via: [:get, :post]

  get "admin" => redirect("/admin/site")

  namespace :admin do
    resource :confirmation_email
    resources :races do
      resources :bonuses do
        put "", action: :sortable, on: :collection
        post :delete_all, on: :collection
      end
      resources :teams, except: :show do
        post :send_confirmation_emails, :on => :collection
      end
    end
    resources :users do
      post :resend_confirmation
    end
    resource :database
  end
end

app/models/race.rb
require "active_record/json_associations"

class Race < ActiveRecord::Base
  belongs_to_many :categories, class_name: "TeamCategory"
  has_many :teams
  has_many :riders, :through => :teams
  has_many :points

  store :settings

  serialize :shirt_sizes, coder: JSON, type: Array, default: %w[XS S M L XL XXL XXXL]

  def self.published
    where(published: true).order(year: :desc)
  end

  def self.current
    last
  end

  def running?
    started? and not finished?
  end

  def started?
    DateTime.now > start_time
  end

  def finished?
    DateTime.now > end_time
  end

  def end_time
    start_time + 24.hours
  end

  def bonuses
    settings[:bonuses] ||= []
  end

  def bonuses= value
    settings[:bonuses] = value
  end

  def bonus_checkpoints
    bonuses.map.with_index do |attributes, index|
      Bonus.new(attributes.merge(id: index))
    end
  end

  def assign_all_bonuses_bonuses
    tattoo_points = bonus_checkpoints.first.points.to_i
    raise AllBonusesException, "The first bonus needs to be a five point tattoo bonus" unless tattoo_points == 5
    all_bonuses_points = bonus_checkpoints.last.points.to_i
    raise AllBonusesException, "The last bonus needs to be a five point all bonuses bonus" unless all_bonuses_points == 5

    teams.find_each do |team|
      assigned_bonuses = team.points.bonuses.map(&:bonus_id).sort
      before = (1..bonus_checkpoints.count-2).to_a
      after = (1..bonus_checkpoints.count-1).to_a
      all_bonuses_bonus = team.points.where(qty: 5, category: "Bonus", race: self, bonus_id: bonus_checkpoints.last.id)

      if [before, after].include?(assigned_bonuses)
        all_bonuses_bonus.first_or_create!
      else
        all_bonuses_bonus.destroy_all
      end
    end
  end

  def total_laps
    points.laps.sum(:qty)
  end

  def total_miles
    total_laps * BigDecimal("4.6")
  end

  def shirt_size_counts
    teams.inject({}) do |counts, team|
      team.shirt_sizes.attributes.each do |size, count|
        counts[size.to_s] ||= 0
        counts[size.to_s] += count.to_i
      end
      counts
    end
  end

  def rider_autocomplete_options
    user_team_map = riders.includes(:team).inject({}) do |map, rider|
      if rider.user_id
        map.merge rider.user_id => rider.team.position
      else
        map
      end
    end

    User.all.map do |user|
      {
        verified: user.verified?,
        label: "#{user.name} ‹#{user.email}›",
        value: user.id,
        user_id: user.id,
        name: user.name,
        email: user.email,
        phone: user.phone,
        shirt_size: user.shirt_size,
        team_pos: user_team_map[user.id],
      }
    end
  end
end

class AllBonusesException < StandardError; end

app/models/team.rb
require "acts_as_list"
require "shirt_sizes"

class Team < ActiveRecord::Base
  def self.allowed_ranges
    Category.all.to_a.reduce({}) do |hash, category|
      hash.merge category.key => category.range
    end
  end

  def self.legacy_categories
    Category.pluck(:name)
  end

  default_scope -> { order(:position) }
  
  def self.by_category category
    where(category: category)
  end

  attr_accessor :phone

  belongs_to :race
  belongs_to :category, class_name: "TeamCategory"
  has_many :riders, dependent: :delete_all, inverse_of: :team
  accepts_nested_attributes_for :riders, reject_if: ->(attrs) { attrs["name"].blank? }, allow_destroy: true

  has_many :points

  serialize :shirt_sizes, coder: ShirtSizes
  def shirt_sizes
    if shirt_sizes_before_type_cast.nil?
      self.shirt_sizes = default_shirt_sizes
      super
    else
      super
    end
  end

  def shirt_sizes= value
    value = ShirtSizes.new(value.transform_values(&:to_i)) if value.is_a?(Hash)
    super
  end

  def default_shirt_sizes
    race.shirt_sizes.reduce({}) { |h,k| h[k]=0; h }
  end

  validates_presence_of :race, :name, :category
  validates_uniqueness_of :position, :scope => :race_id
  validates_each :riders do |record, attr, value|
    record.errors.add attr, "count is incorrect." unless record.allowed_range.include?(value.length)
  end

  acts_as_list :scope => :race_id

  before_save :assign_phone_to_captain

  def self.leader_board
    includes(:points).sort do |a,b|
      comp = a.points_total <=> b.points_total
      comp == 0 ? a.position <=> b.position : comp
    end.reverse
  end

  def self.send_confirmation_email_by_ids team_ids
    Team.where(id: team_ids).each do |team|
      team.delay.send_confirmation_email!
    end
  end

  delegate :year, to: :race, prefix: true

  def send_confirmation_email!
    Mailer.confirmation_email(self).deliver_now
    update_attribute :confirmation_sent_at, Time.now
  end

  def laps_total
    points.laps.sum(:qty)
  end

  def miles_total
    laps_total * BigDecimal("4.6")
  end

  def bonuses_total
    points.bonuses.sum(:qty)
  end

  def penalties_total
    points.penalties.sum(:qty)
  end

  def points_total
    points.sum(:qty)
  end

  def allowed_range
    category.range
  end

  def captain
    riders.first
  end

  def captain_email
    captain.email
  end

  def lieutenants
    riders - [captain]
  end

  def lieutenant_emails
    lieutenants.collect(&:email).select(&:present?).join(", ")
  end

  def category_initial
    category.initial
  end

  def legacy_category_initial_with_gender
    return "E" if category_name =~ /elder/i
    return category_initial unless category_initial == "S"
    category_name =~ /female/ ? "F" : "M"
  end

  def category_name
    category.name
  end

  def position_and_name
    "#{position} - #{name}"
  end

  def paid?
    riders.all?(&:paid?)
  end

  def partially_paid?
    not paid? and riders.any?(&:paid)
  end

  def emailed?
    confirmation_sent_at.present?
  end

  def has_bonus? bonus
    points.bonuses.map(&:bonus_id).include?(bonus.id)
  end

  def to_paypal_hash
    {
      :no_shipping => "1",
      :business => "riverwest24@gmail.com",
      :amount => 20.00,
      :quantity => riders.length,
      :item_name => "Riverwest 24 Registration - #{category.name}",
      :cmd => "_xclick",
      :custom => id,
      :return => "http://riverwest24.com/join/articles/thanks",
      :notify_url => "http://riverwest24.com/join/registrations/payment",
      :shopping_url => "http://riverwest24.com",
      :cancel_return => "http://riverwest24.com",
      :upload => "1",
      :currency_code => "USD",
      :no_note => "1",
      :address_override => "1"
    }
  end

  private

  def assign_phone_to_captain
    captain.phone = self.phone if self.phone
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::BaseController
  before_action :authorize_access
  before_action :set_race

  def index
    @teams = @race.teams.includes(:category, :riders)
  end

  def new
    @team = @race.teams.build
    render :form
  end

  def edit
    @team = @race.teams.find(params[:id])
    render :form
  end

  def create
    @team = @race.teams.build(team_params)
    if @team.save
      redirect_to [:edit, :admin, @race, @team], notice: "The team has been created."
    else
      flash.now.alert = errors_for(@team)
      render :form
    end
  # teams.position uniqueness constraint can fail at db level, so just try again
  rescue ActiveRecord::StatementInvalid
    retry
  end

  def update
    @team = @race.teams.find(params[:id])
    if @team.update(team_params)
      redirect_to [:edit, :admin, @race, @team], notice: "The team has been updated."
    else
      flash.now.alert = errors_for(@team)
      render :form
    end
  end

  def destroy
    @team = @race.teams.find(params[:id])
    # prevent positions from being updated
    # TODO: replace acts_as_list with autopopulating position column and call it a day?
    Team.acts_as_list_no_update do
      @team.destroy
    end
    redirect_to [:admin, @race, :teams], notice: "The team has been destroyed."
  end

  def send_confirmation_emails
    Team.send_confirmation_email_by_ids params[:team_ids]
    redirect_to [:admin, @race, :teams], notice: "Confirmation emails sending!"
  end

  private

  def set_menu
    @menu = Menus::Admin::Teams.new
  end

  def set_race
    @race = Race.find(params[:race_id])
  end

  def authorize_access
    redirect_to admin_sites_url unless @site || current_user.admin?
  end

  def team_params
    params[:team].permit!.to_h
  end
end

app/controllers/teams_controller.rb
class TeamsController < BaseController
  before_action :set_race
  before_action :guess_section

  def index
    @teams = @race.teams.leader_board
    respond_to do |format|
      format.html
      format.js { render @teams, :layout => false }
    end
    expires_in 1.minute, public: true if Rails.env.production?
  end

  def show
    @team = @race.teams.find_by_position! params[:position]
  end

  private

  def set_race
    @race = Race.find_by_year(params[:year]) || Race.current
  end
end

app/views/admin/teams/_fields.html.slim
h4 Team Information
.flex
  - if form.object.persisted?
    .field = form.number_field :position, label: "POS#", class: "xlarge"

  .field
    = form.label :category_id, "Category"
    = form.select :category_id, {}, { prompt: form.object.new_record? }, data: { controller: "team-category-selector" }, required: true do
      - form.object.race.categories.each do |category|
        = content_tag :option, category.name, value: category.id, data: { min: category.min, max: category.max }, selected: form.object.category_id == category.id

.field = form.text_field :name, label: "Team Name", class: "xlarge"

fieldset
  .rider-flex
    - if @menu # is backend
      javascript:
        window.riderAutocompleteOptions = #{raw form.object.race.rider_autocomplete_options.to_json};
    = form.fields_for :riders do |rider_form|
      = render "admin/teams/rider_fields", form: rider_form
    - if @menu # is backend
      .add-rider-link
        = link_to_add_association "Add rider", form, :riders

- if @menu # is backend
  - if form.object.race.year >= 2018
    .field
      = form.label :shirt_sizes
      = form.fields_for :shirt_sizes, form.object.shirt_sizes do |shirt_sizes_form|
        .all-shirt-fields
          .field
            h4 Sizes
            .shirt-fields
              - form.object.race.shirt_sizes.each do |size|
                .field
                  = shirt_sizes_form.label size.to_sym, size
                  = shirt_sizes_form.number_field size.to_sym, data: { shirt_sizes_target: "output" }

app/views/admin/teams/_rider_fields.html.slim
- form ||= f
fieldset.field.nested-fields.rider-field data-controller=("autocomplete" if @menu)
  div
    - if @menu # is backend
      .remove-rider
        = link_to_remove_association form do
          span Removes rider

    h4 Rider
    - if @menu # is backend
      .field
        label for="team_riders_attributes_#{form.index}_search" Search
        input.autocomplete-input id="team_riders_attributes_#{form.index}_search" data-autocomplete-target="field"
        = form.hidden_field :user_id
    - else
        input type="hidden" data-autocomplete-target="field"

    .field = form.check_box :paid, label: "Paid?"
    .field = form.text_field :name, label: true
    .field = form.text_field :email, label: true
    .field = form.text_field :phone, label: true
    .field = form.select :shirt_size, form.object.team.race.shirt_sizes, { include_blank: true}, { label: "Shirt size", data: { shirt_sizes_target: "input", action: "shirt-sizes#render" } }
    .field = form.text_area :notes, label: true

app/views/admin/teams/form.html.haml
= error_messages_for @team, object_name: "team"

= form_for [:admin, @site, @race, @team] do |form|
  = form.hidden_field :race_id
  %h2
    = form.object.new_record? ? "New" : "Edit"
    Team

  %fieldsets
    %h4 Team Information
    - if form.object.persisted?
      .field= form.number_field :position, label: "POS#", class: "xlarge"

    .field
      = form.label :category_id, "Category"
      = form.select :category_id, {}, { prompt: form.object.new_record? }, data: { "team_category_select" => ".nested-fields" } do
        - TeamCategory.all.each do |category|
          = content_tag :option, category.name, value: category.id, data: { min: category.min, max: category.max }

    .field= form.text_field :name, label: "Team Name", class: "xlarge"
    - if @race.year >= 2018
      .field= render "shirt_sizes", form: form

  %fieldset
    .info-text To remove riders, highlight the <i class="fa fa-trash"></i> icon and press Save.
    .rider-flex
      = form.fields_for :riders do |rider_form|
        = render "rider_fields", form: rider_form
      .add-rider-link= link_to_add_association "Add rider", form, :riders

  %hr

  .field
    - save_or_cancel_links form, cancel_url: [:admin, @site, @race, :teams]

app/views/admin/teams/form.html.slim
= error_messages_for @team

= content_for :body_class, "team-edit-body"

= form_for [:admin, @race, @team], data: { controller: "shirt-sizes" } do |form|
  = form.hidden_field :race_id
  h2
    = form.object.new_record? ? "New" : "Edit"
    |  Team

  = render "fields", form: form

  hr

  .field
    = submit_tag "Save", id: "commit", data: { disable_with: "Saving..." }
    | or&nbsp;
    = link_to "Cancel", [:admin, @race, :teams]

app/views/admin/teams/index.html.haml
%h2 #{@race.year} Teams

= form_tag send_confirmation_emails_admin_race_teams_path(@race) do
  %header
    %input.send(type="submit" value="Send Confirmation Emails to Selected")
    = link_to "Edit Confirmation Email", edit_admin_confirmation_email_path, class: "edit-button"

  %p
    Teams:
    %b= @race.teams.count
    &nbsp;
    Racers:
    %b= @race.riders.count

  %table.team-list
    %thead
      %tr
        %th
        %th Paid
        %th Emailed
        %th POS#
        %th Class
        %th Team Name
        %th Riders
        %th T-Shirts
        %th Leader Name
        %th
    %tbody
      - @teams.each do |team|
        %tr
          %td
            %label{ :for => "team_#{team.id}", :style => "display: none" }= team.name
            %input{ :type => "checkbox", :name => "team_ids[]", :value => team.id, :id => "team_#{team.id}" }
          %td
            - if team.paid?
              .paid Yes
            - elsif team.partially_paid?
              == #{team.riders.select(&:paid?).size}/#{team.riders.size}
            - else
              .unpaid No
          %td
            - if team.emailed?
              .emailed Yes
            - else
              .not_emailed No
          %td= team.position
          %td=h team.category_initial
          %td= link_to h(team.name), [:edit, :admin, @race, team]
          %td= team.riders.size
          %td{ class: "#{"missing-shirts" if team.riders.size != team.shirt_sizes.total }"}
            = team.shirt_sizes.total
          %td
            - if team.captain
              = mail_to team.captain.email, h(team.captain.name), :cc => team.lieutenant_emails, :subject => team.position_and_name
            - else
              = team.name
          %td.actions
            = link_to "Edit", [:edit, :admin, @race, team], :class => "edit"
            = link_to "Delete", [:admin, @race, team], :class => 'delete', :method => :delete, :data => { :confirm => 'Are you sure you want to delete this team and all its riders?' }

  %input(type="submit" value="Send Confirmation Emails to Selected")

= content_for :sidebar do
  .tabs
    .tab.active
      %h3 Totals

      %p
        Teams:
        %b= @race.teams.count
        &nbsp;
        Racers:
        %b= @race.riders.count

      %p
        %ul
          - Category.all.each do |category|
            %li
              = category.name
              %b= @race.teams.by_category(category).count

        Shirts:
        %table.shirts-count
          - @race.shirt_size_counts.each do |size, count|
            %tr
              %td(style="padding-right: 5px")
                %b= size
              %td= count

      %p= button_to "Download Database", [:admin, :database, format: :sql], method: :get
      %p= button_to "Export Teams", [:admin, @race, :teams, format: :csv], method: :get

app/views/admin/teams/new.html.haml
= error_messages_for @team, object_name: "team"

= form_for [:admin, @site, @race, @team] do |form|
  = form.hidden_field :race_id
  %h2 New / Edit Team

  %fieldset
    %h4 Team Information
    / MICAH - can POS# be set upon team creation?
    .field= form.number_field :position, label: "POS#", class: "xlarge"
    .field= form.select :category, Team.categories, label: true
    .field= form.text_field :name, label: "Team Name", class: "xlarge"
    .field= render "shirt_sizes", form: form

  %fieldset
    .rider-flex
      - i = 1
      = form.fields_for :riders do |rider_form|
        .field
          %fieldset{ id: "rider_#{i}" }
            %h4
              Rider #{i}
              = "/ Team Leader" if i == 1
            .field= rider_form.check_box :paid, label: "Paid?"
            .field= rider_form.text_field :name, label: true
            .field= rider_form.text_field :email, label: true
            .field= rider_form.text_field :phone, label: true
            .field= rider_form.text_area :notes, label: true

        - i += 1

      / MICAH - IF EDITING, CAN ADD RIDERS UP TO 6?
      /.field= link_to "+ Add a rider", [:new, :admin, @site, @race, @team, :rider]


  %hr

  - save_or_cancel_links form, cancel_url: [:admin, @site, @race, :teams]